[package]
name = "gcm_verification"
version = "0.1.0"
authors = ["Sebastian <asamk@gmx.de>"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures = "0.1"
http = "0.1"
hyper = "0.12"
hyper-tls = "0.3"
native-tls = "0.2"
tokio-io = "0.1"
tokio-tls = "0.2"
quick-protobuf = "0.6.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"

[dependencies.tokio]
version="0.1"
features=["async-await-preview"]
